#FSR Autogenerated Content. DO NOT DELETE
from .get_user_details import get_user_details
from .delete_user import delete_user
from .add_user import add_user
from .update_user import update_user
from .get_group_details import get_group_details
from .delete_group import delete_group
from .add_group import add_group
from .update_group import update_group
 
supported_operations = {'get_user_details': get_user_details, 'delete_user': delete_user, 'add_user': add_user, 'update_user': update_user, 'get_group_details': get_group_details, 'delete_group': delete_group, 'add_group': add_group, 'update_group': update_group, }