"""
Copyright start
MIT License
Copyright (c) 2023 Fortinet Inc
Copyright end
"""
# FSR Autogenerated Content. DO NOT DELETE
from .get_user_list import get_user_list
from .delete_user import delete_user
from .create_user import create_user
from .update_user_details import update_user_details
from .get_group_list import get_group_list
from .delete_group import delete_group
from .create_group import create_group
from .update_group_members import update_group_members

supported_operations = {
    'get_user_list': get_user_list,
    'delete_user': delete_user,
    'create_user': create_user,
    'update_user_details': update_user_details,
    'get_group_list': get_group_list,
    'delete_group': delete_group,
    'create_group': create_group,
    'update_group_members': update_group_members
}
